### ISSUE TITLE
Frontend development of honey lens

### ISSUE THREAD

**Issue by philip-ifeanyi** [zuri-training/my-cms-pjt19#10]
https://www.figma.com/proto/4T9P5cUlMpWiw4XCqt6CVH/Optimus-CMS?page-id=0%3A1&node-id=297%3A124&viewport=1308%2C-1264%2C0.16&scaling=min-zoom&starting-point-node-id=102%3A23

**Comment by moabah** [comment]
Done. https://github.com/zuri-training/my-cms-pjt19/pull/30
