### ISSUE TITLE
frontend development of ironside

### ISSUE THREAD

**Issue by philip-ifeanyi** [zuri-training/my-cms-pjt19#11]
https://www.figma.com/proto/4T9P5cUlMpWiw4XCqt6CVH/Optimus-CMS?page-id=0%3A1&node-id=605%3A271&viewport=1838%2C-867%2C0.12&scaling=contain&starting-point-node-id=297%3A124

**Comment by Waga43** [comment]
Noted TL

**Comment by Waga43** [comment]
Task completed.  @philip-ifeanyi

**Comment by Waga43** [comment]
Would gladly help out with any other tasks if i can. @philip-ifeanyi

**Comment by Gmhyke** [comment]
Thanks @Waga43

**Comment by sneekywhite** [comment]
nice template

**Comment by Lateefah1kk** [comment]
Thanks @Waga43

**Comment by Waga43** [comment]
You are welcome guys. The pleasure is mine. Wish us all the best. Let's keep the spirit high.

**Comment by philip-ifeanyi** [comment]
Confirmed done
