### ISSUE TITLE
frontend development of chop chop

### ISSUE THREAD

**Issue by philip-ifeanyi** [zuri-training/my-cms-pjt19#12]
https://www.figma.com/proto/4T9P5cUlMpWiw4XCqt6CVH/Optimus-CMS?page-id=0%3A1&node-id=18%3A24&viewport=1471%2C-4406%2C0.13&scaling=contain&starting-point-node-id=297%3A124&show-proto-sidebar=1

**Comment by Ogunsuyioluwaseeni** [comment]
Noted with immediate action
