### ISSUE TITLE
frontend development of smart studio

### ISSUE THREAD

**Issue by philip-ifeanyi** [zuri-training/my-cms-pjt19#13]
https://www.figma.com/proto/4T9P5cUlMpWiw4XCqt6CVH/Optimus-CMS?page-id=0%3A1&node-id=119%3A25&viewport=1308%2C-1264%2C0.16&scaling=min-zoom&starting-point-node-id=102%3A23

**Comment by JUNNY12** [comment]
Noted , it will be done as quick as possible
