### ISSUE TITLE
Design UI/UX for Photography portfolio, landing page and Travel blog landing page

### ISSUE THREAD

**Issue by philip-ifeanyi** [zuri-training/my-cms-pjt19#17]
https://www.figma.com/file/4T9P5cUlMpWiw4XCqt6CVH/Team_19_MyCMS?node-id=0%3A1

Art of food
Ade Ola wedding photography

**Comment by Amelia-O** [comment]
1. [ ]

**Comment by Koawhyte** [comment]
Photography landing page done

https://www.figma.com/proto/Om7D1Ot91oMH3xeypiQw0q/Team_19_MyCMS-(Copy)?page-id=0%3A1&node-id=119%3A25&viewport=-3132%2C-1631%2C0.06&scaling=scale-down&starting-point-node-id=42%3A2&show-proto-sidebar=1
