### ISSUE TITLE
Design UI/UX for Photography Landing page

### ISSUE THREAD

**Issue by philip-ifeanyi** [zuri-training/my-cms-pjt19#18]
https://www.figma.com/file/4T9P5cUlMpWiw4XCqt6CVH/Team_19_MyCMS?node-id=0%3A1

**Comment by chideraN** [comment]
designed the photography landing page
https://www.figma.com/file/4T9P5cUlMpWiw4XCqt6CVH/Team_19_MyCMS?node-id=161%3A72

**Comment by Koawhyte** [comment]
Smart Studio photography landing page  done


https://www.figma.com/proto/Om7D1Ot91oMH3xeypiQw0q/Team_19_MyCMS-(Copy)?page-id=0%3A1&node-id=119%3A25&viewport=-3132%2C-1631%2C0.06&scaling=scale-down&starting-point-node-id=42%3A2&show-proto-sidebar=1

**Comment by Koawhyte** [comment]
Designed Smart Studio photography landing page

https://www.figma.com/file/4T9P5cUlMpWiw4XCqt6CVH/Team_19_MyCMS?node-id=161%3A72

**Comment by Koawhyte** [comment]
Designed Smart Studio photography Landing page

https://www.figma.com/proto/Om7D1Ot91oMH3xeypiQw0q/Team_19_MyCMS-(Copy)?page-id=0%3A1&node-id=119%3A25&viewport=-3132%2C-1631%2C0.06&scaling=scale-down&starting-point-node-id=42%3A2&show-proto-sidebar=1

**Comment by Koawhyte** [comment]
Designed Smart Studio a photography landing page

https://www.figma.com/file/Om7D1Ot91oMH3xeypiQw0q/Team_19_MyCMS-(Copy)?node-id=119%3A25

**Comment by Koawhyte** [comment]
Designed responsive mobile screen fore smart studio


https://www.figma.com/file/Om7D1Ot91oMH3xeypiQw0q/Team_19_MyCMS-(Copy)?node-id=2636%3A1408

**Comment by Koawhyte** [comment]
Designed Jane Daniels photography portfolio

https://www.figma.com/file/Om7D1Ot91oMH3xeypiQw0q/Team_19_MyCMS-(Copy)?node-id=1293%3A838

**Comment by Koawhyte** [comment]
Mobile screen for Jane Daniel photography portfolio


https://www.figma.com/file/Om7D1Ot91oMH3xeypiQw0q/Team_19_MyCMS-(Copy)?node-id=2283%3A8768

**Comment by Koawhyte** [comment]
Designed Favour Nelson photography portfolio

https://www.figma.com/file/Om7D1Ot91oMH3xeypiQw0q/Team_19_MyCMS-(Copy)?node-id=1234%3A459

**Comment by Koawhyte** [comment]
Designed mobile screen for favor Nelson photography portfolio


https://www.figma.com/file/Om7D1Ot91oMH3xeypiQw0q/Team_19_MyCMS-(Copy)?node-id=2283%3A8580
