### ISSUE TITLE
Design UI/UX for Portfolio Design Template

### ISSUE THREAD

**Issue by philip-ifeanyi** [zuri-training/my-cms-pjt19#20]
https://www.figma.com/file/4T9P5cUlMpWiw4XCqt6CVH/Team_19_MyCMS?node-id=0%3A1

**Comment by Lateefah1kk** [comment]
https://www.figma.com/file/Om7D1Ot91oMH3xeypiQw0q/Team_19_MyCMS-(Copy)?node-id=18%3A26

**Comment by Lateefah1kk** [comment]
designed mobile responsiveness
https://www.figma.com/file/Om7D1Ot91oMH3xeypiQw0q/Team_19_MyCMS-(Copy)?node-id=2283%3A9811

**Comment by Lateefah1kk** [comment]
https://www.figma.com/file/Om7D1Ot91oMH3xeypiQw0q/Team_19_MyCMS-(Copy)?node-id=2190%3A2840
