### ISSUE TITLE
Design UI/UX for Blog Templates

### ISSUE THREAD

**Issue by philip-ifeanyi** [zuri-training/my-cms-pjt19#22]
- [ ] Design UI/UX for Design Template
- [ ] #23

**Comment by philip-ifeanyi** [comment]
- [ ] Design UI/UX for Food Template

**Comment by philip-ifeanyi** [comment]
- [ ] Design UI/UX for Food Template

**Comment by TosinTaiyeSolanke** [comment]
Designs for blog templates webpage
https://www.figma.com/file/Om7D1Ot91oMH3xeypiQw0q/Team_19_MyCMS-(Copy)?node-id=2637%3A1407

designs for blog templates mobile responsiveness
https://www.figma.com/file/Om7D1Ot91oMH3xeypiQw0q/Team_19_MyCMS-(Copy)?node-id=2676%3A1409
