### ISSUE TITLE
create database schemas

### ISSUE THREAD

**Issue by philip-ifeanyi** [zuri-training/my-cms-pjt19#3]

**Comment by philip-ifeanyi** [comment]
[https://www.figma.com/file/uus1F7ZcjcFcDjTcUBaAXV/UML-Diagrams?node-id=3%3A51](url)

**Comment by philip-ifeanyi** [comment]
https://www.figma.com/file/uus1F7ZcjcFcDjTcUBaAXV/UML-Diagrams?node-id=3%3A51

**Comment by Waga43** [comment]
Noted TL.
