### ISSUE TITLE
Frontend development of haul point

### ISSUE THREAD

**Issue by philip-ifeanyi** [zuri-training/my-cms-pjt19#9]
https://www.figma.com/proto/4T9P5cUlMpWiw4XCqt6CVH/Optimus-CMS?page-id=0%3A1&node-id=18%3A20&viewport=1308%2C-1264%2C0.16&scaling=min-zoom&starting-point-node-id=102%3A23

**Comment by IfeoluwaAroboto** [comment]
Working on it.

**Comment by philip-ifeanyi** [comment]
Checked and working
